apps/core/urls.py
from django.urls import path
from apps.core.views.dashboard_views import *
from apps.core.views.deportistas.deportistas_views import *

app_name='core'
urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name='Dashboard'),
    path('deportistas/list/', DeportistasListView.as_view(), name="Deportistas_list"),
    path('gracias/', gracias.as_view(), name='gracias')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from apps.login.views import LoginFormView

urlpatterns = [
    path('', include('apps.login.urls')),
    path('login/', include('apps.login.urls')),
    path('admin/', admin.site.urls),
    path('create/', include('apps.register.urls')),
    path('core/', include('apps.core.urls'))
]

templates/Registro.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="icon" href="{% static 'img/tabicon.png' %}" type="image/png"/>
    <title>SI-CRD | UV</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/fontawesome-6.3.0/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/plugins/font-awesome-5.11.1/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.0.4/js/adminlte.min.js' %}"></script>
    <!-- Sweetalert2 -->
    <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
    <!-- Jquery Confirm -->
    <link rel="stylesheet" href="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
    <script src="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
    <!-- My css -->
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <!-- Functions -->
    <script src="{% static 'js/functions.js' %}"></script>
    <!-- Block head -->

</head>
{% block body %}

{% endblock %}
</html>

templates/body.html
{% extends 'home.html' %}
{% block body %}
    <body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Header -->
        {% include 'header.html' %}
        <!-- Sidebar -->
        {% include 'sidebar.html' %}
        <!-- Content -->
        <div class="content-wrapper">
            <div class="content-header">
                <div class="container-fluid">
                    <div class="row">
                        <div class="col-sm-6">
                            <h1 class="m-0 text-dark"> Bienvenido <small>{{ request.user.get_full_name }}</small></h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="{% url 'core:Dashboard' %}">Home</a></li>
                                <li class="breadcrumb-item"><a href="{{ list_url }}">{{ entity }}</a></li>
                            </ol>
                        </div>
                    </div>
                </div>
            </div>
            <div class="content">
                <div class="container-fluid">
                    {% block content %}

                    {% endblock %}
                </div>
            </div>
        </div>
        <!-- Footer -->
        {% include 'footer.html' %}
    </div>
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    <script>
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
    </body>
{% endblock %}

templates/cuerpo.html
{% extends 'Registro.html' %}
{% block body %}
    {% block head_form %}

    {% endblock %}

    {% block content %}
    
    {% endblock  %}
    <!-- Block javascript -->
    {% block javascript %}

    {% endblock %}
    <script>
        {% if messages %}
            var html = '<p>';
            {% for message in messages %}
                html += '{{ message }}<br>';
            {% endfor %}
            html += '</p>';
            Swal.fire({
                title: 'Error!',
                html: html,
                icon: 'error'
            });
        {% endif %}
    </script>
{% endblock %}

templates/delete.html
{% extends 'body.html' %}
{% load widget_tweaks %}
{% block content %}
    <form method="post" action=".">
        <div class="card card-light">
            <div class="card-header">
                <h3 class="card-title">
                    <i class="fas fa-trash"></i>
                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                {% csrf_token %}
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                <div class="alert alert-danger alert-dismissible">
                    <h5><i class="icon fas fa-ban"></i> Notificación!</h5>
                    ¿Estas seguro de eliminar el registro?
                </div>
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-save"></i> Si, aceptar
                </button>
                <a href="{{ list_url }}" class="btn btn-danger">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    <script>
        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);
            submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de eliminar el siguiente registro?', parameters, function () {
                location.href = '{{ list_url }}';
            });
        });
    </script>
{% endblock %}

templates/footer.html
<!-- Main Footer -->
<footer class="main-footer text-center">
    <strong>SI-CRD</strong><br>
    
</footer>

templates/form.html
{% extends 'body.html' %}
{% load static %}
{% load widget_tweaks %}

{% block head %}

    {% block head_form %}
    {% endblock %}
    
{% endblock %}

{% block content %}
    <form method="post" action="." enctype="multipart/form-data">
        {% csrf_token %}
        <div class="card card-light">
            <div class="card-header">
                <h3 class="card-title">
                    {% if action == 'add' %}
                        <i class="fas fa-plus"></i>
                    {% else %}
                        <i class="fas fa-edit"></i>
                    {% endif %}

                    {{ title }}
                </h3>
            </div>
            <div class="card-body">
                <input type="hidden" name="action" value="{{ action }}">
                {% if form.errors %}
                    <div class="alert alert-danger alert-dismissible">
                        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                        <h5><i class="icon fas fa-ban"></i> Ha ocurrido un error al querer guardar el registro</h5>
                        <ul>
                            {% for field in form %}
                                {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                {% endfor %}
                            {% endfor %}
                        </ul>
                    </div>
                {% endif %}
                {% for field in form.visible_fields %}
                    <div class="form-group">
                        <label for="email">{{ field.label }}:</label>
                        {{ field|add_class:'form-control'|attr:'autocomplete:off' }}
                    </div>
                {% endfor %}
            </div>
            <div class="card-footer">
                <button type="submit" class="btn btn-primary">
                    <i class="fas fa-save"></i> Guardar registro
                </button>
                <a href="{{ list_url }}" class="btn btn-danger">
                    <i class="fas fa-times"></i> Cancelar
                </a>
            </div>
        </div>
    </form>
    <script>
        {% if form.errors %}
            var errors = '';
            {% for field in form %}
                {% for error in field.errors %}
                    errors += '{{ error }}\n';
                {% endfor %}
            {% endfor %}
            {% for error in form.non_field_errors %}
                errors += '{{ error }}\n';
            {% endfor %}
            Swal.fire({
                title: 'Error!',
                text: errors,
                icon: 'error'
            });
        {% endif %}

        $('form').on('submit', function (e) {
            e.preventDefault();
            var parameters = new FormData(this);
            submit_with_ajax(window.location.pathname, 'Notificación', '¿Estas seguro de realizar la siguiente acción?', parameters, function () {
                location.href = '{{ list_url }}';
            });
        });
    </script>
{% endblock %}

templates/header.html
<nav class="main-header navbar navbar-expand navbar-dark navbar-dark">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
        <li class="nav-item d-none d-sm-inline-block">
            <a href="{% url 'core:Dashboard' %}" class="nav-link">Home</a>
        </li>
    </ul>
    <ul class="navbar-nav ml-auto">
        <li class="nav-item text-white">
            <a class="nav-link" href="#">
                {{ request.user.groups.first }}
            </a>
        </li>
        <li class="nav-item dropdown">
            <a class="nav-link" data-toggle="dropdown" href="#">
                <i class="fas fa-users-cog"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-lg dropdown-menu-right">
                    <span class="dropdown-header" style="font-size: 12px;">
                        Sú último acceso fue {{ request.user.last_login }}
                    </span>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-edit mr-2"></i> Editar perfil
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item">
                    <i class="fas fa-lock mr-2"></i> Editar password
                </a>
                <div class="dropdown-divider"></div>
                <a href="#" class="dropdown-item dropdown-footer">
                    <p>Este sistema te permitira realizar diferentes actividades</p>
                </a>
            </div>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'logout' %}">
                <i class="fas fa-power-off" aria-hidden="true"></i>
            </a>
        </li>
    </ul>
</nav>

templates/home.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <link rel="icon" href="{% static 'img/tabicon.png' %}" type="image/png"/>
    <title>SI-CRD | UV</title>
    <!-- Font Awesome Icons -->
    <link rel="stylesheet" href="{% static 'lib/fontawesome-6.3.0/css/all.css' %}">
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/plugins/font-awesome-5.11.1/css/all.min.css' %}">
    <!-- Theme style -->
    <link rel="stylesheet" href="{% static 'lib/adminlte-3.0.4/css/adminlte.min.css' %}">
    <!-- Google Font: Source Sans Pro -->
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700" rel="stylesheet">
    <!-- jQuery -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/jquery/jquery.min.js' %}"></script>
    <!-- Bootstrap 4 -->
    <script src="{% static 'lib/adminlte-3.0.4/plugins/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
    <!-- AdminLTE App -->
    <script src="{% static 'lib/adminlte-3.0.4/js/adminlte.min.js' %}"></script>
    <!-- Sweetalert2 -->
    <script src="{% static 'lib/sweetalert2-9.10.0/sweetalert2.all.min.js' %}"></script>
    <!-- Jquery Confirm -->
    <link rel="stylesheet" href="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.css' %}">
    <script src="{% static 'lib/jquery-confirm-v3.3.4/jquery-confirm.min.js' %}"></script>
    <!-- My css -->
    <link rel="stylesheet" href="{% static 'css/mystyle.css' %}">
    <!-- Functions -->
    <script src="{% static 'js/functions.js' %}"></script>
    <!-- Block head -->
    {% block head %}

    {% endblock %}
</head>
{% block body %}

{% endblock %}
</html>

templates/list.html
{% extends 'body.html' %}
{% load static %}
{% block head %}
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/css/dataTables.bootstrap4.min.css' %}"/>
    <link rel="stylesheet" href="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/css/responsive.bootstrap4.min.css' %}"/>
    <script src="{% static 'lib/datatables-1.10.20/js/jquery.dataTables.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/js/dataTables.bootstrap4.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/dataTables.responsive.min.js' %}"></script>
    <script src="{% static 'lib/datatables-1.10.20/plugins/responsive-2.2.3/js/responsive.bootstrap4.min.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11.0.19/dist/sweetalert2.min.js"></script>
    {% block head_list %}
    {% endblock %}
{% endblock %}

{% block content %}
    <div class="card card-light">
        <div class="card-header">
            <h3 class="card-title">
                <i class="fas fa-search"></i>
                {{ title }}
            </h3>
        </div>
        <div class="card-body">
            <table class="table table-striped table-bordered table-hover" id="tableData" style="width:100%">
                <thead>
                    {% block columns %}
                    {% endblock %}
                </thead>
                <tbody>
                    {% block rows %}
                    {% endblock %}
                </tbody>
            </table>
        </div>
        <div class="card-footer">
            {% block buttons_list %}
                <a href="{{ create_url }}" class="btn btn-primary">
                    <i class="fas fa-plus"></i> Nuevo registro
                </a>
                <a href="{{ list_url }}" class="btn btn-success">
                    <i class="fa-solid fa-rotate"></i> Actualizar
                </a>
            {% endblock %}
        </div>
    </div>
{% endblock %}

{% block javascript %}
    <script type="application/javascript">
        $(function () {
            $('#data').DataTable({
                responsive: true,
                autoWidth: false
            });
        });
    </script>
{% endblock %}

templates/sidebar.html
{% load static %}
<aside class="main-sidebar sidebar-light-primary elevation-4">
    <a href="#" class="brand-link">
    </a>
    <div class="sidebar">
        <div class="user-panel mt-3 pb-3 mb-3 d-flex">
            <div class="image">
                <img src="{% static 'img/user.jpg' %}" class="img-circle" alt="User Image">
            </div>
            <div class="info">
                <a href="#" class="d-block">{{ request.user.username }}</a>
            </div>
        </div>
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-solid fa-house"></i>
                        <p>Dashboard</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-solid fa-file-signature"></i>
                        <p>REPORTES</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-solid fa-person"></i>
                        <p>CONTRATISTAS</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-solid fa-building-user"></i>
                        <p>
                            ESCENARIOS DEPORTIVOS
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-solid fa-book"></i>
                                <p>RESERVAS</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-solid fa-book-open-reader"></i>
                                <p>INGRESO</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-solid fa-building-user"></i>
                                <p>GESTION</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-solid fa-person-chalkboard"></i>
                        <p>Prestamos</p>
                    </a>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-solid fa-book-bookmark"></i>
                        <p>
                            DEPORTE REPRESENTATIVO
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-solid fa-volleyball"></i>
                                <p>DEPORTISTAS-E</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-solid fa-diamond"></i>
                                <p>DEPORTISTAS-C</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-solid fa-building-user"></i>
                                <p>GESTION</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-solid fa-download"></i>
                                <p>INTERNO</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon fas fa-users"></i>
                        <p>USUARIOS</p>
                    </a>
                </li>
            </ul>
        </nav> 
    </div>
</aside>